# Generated by Django 4.2 on 2023-09-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('username', models.CharField(blank=True, help_text='Username клиента', max_length=50, null=True, verbose_name='Username')),
                ('telegram_id', models.BigIntegerField(help_text='Telegram ID пользователя', verbose_name='Telegram ID')),
                ('name', models.CharField(help_text='Имя в Telegram', max_length=255, verbose_name='Имя в Telegram')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка на пользователя')),
                ('time_notification', models.CharField(default='everyday', verbose_name='Время отправки уведомлений')),
                ('time_user', models.CharField(null=True, verbose_name='Самостоятельное время поль-ля')),
                ('feedbacks_send', models.BooleanField(default=True, verbose_name='Вкл/выкл уведомления для автоматических ответов')),
            ],
            options={
                'verbose_name': 'Клиенты телеграмм бота',
                'verbose_name_plural': 'Клиенты телеграмм бота',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='WbToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, verbose_name='Токен WB пользователя')),
                ('signature_for_answers', models.CharField(max_length=255, null=True, verbose_name='Подпись к ответам на отзывы')),
                ('name_market', models.CharField(max_length=150, null=True, verbose_name='Название магазина пользователя')),
                ('auto_send_star_1', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('auto_send_star_2', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('auto_send_star_3', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('auto_send_star_4', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('auto_send_star_5', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_token', to='telebot.client', verbose_name='Токен WB')),
            ],
            options={
                'verbose_name': 'Магазины телеграмм бота',
                'verbose_name_plural': 'Магазины телеграмм бота',
            },
        ),
        migrations.CreateModel(
            name='ManualGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Текст от пользователя для генерации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='telebot.client', verbose_name='Ручная генерация')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('feedback', models.TextField(verbose_name='Сам отзыв')),
                ('answer', models.TextField(verbose_name='Ответ на отзыв')),
                ('feedback_id', models.CharField(max_length=100, verbose_name='Id отзыва')),
                ('name_item', models.CharField(max_length=100, null=True, verbose_name='Название товара')),
                ('link_photos', models.TextField(null=True, verbose_name='Ссылки на фото отзывов')),
                ('link_feedback', models.CharField(max_length=150, null=True, verbose_name='Ссылка на отзыв')),
                ('day_answer', models.DateTimeField(verbose_name='Дата ответа на отзыв')),
                ('answered_feed', models.BooleanField(default=False, verbose_name='Состояние ответа на отзыв')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_answer', to='telebot.wbtoken', verbose_name='Магазин, которому принадлежит ответ')),
            ],
        ),
    ]
