# Generated by Django 4.2 on 2023-07-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='time_notification',
            field=models.CharField(default='everyday', verbose_name='Время отправки уведомлений'),
        ),
        migrations.AddField(
            model_name='client',
            name='time_user',
            field=models.CharField(null=True, verbose_name='Самостоятельное время поль-ля'),
        ),
        migrations.CreateModel(
            name='WbToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150, verbose_name='Токен WB пользователя')),
                ('signature_for_answers', models.CharField(max_length=255, null=True, verbose_name='Подпись к ответам на отзывы')),
                ('name_market', models.CharField(max_length=150, null=True, verbose_name='Название магазина пользователя')),
                ('auto_send_star_1', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('auto_send_star_2', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('auto_send_star_3', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('auto_send_star_4', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('auto_send_star_5', models.BooleanField(default=False, verbose_name='False, то полуавтоматический режим')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_token', to='telebot.client', verbose_name='Токен WB')),
            ],
            options={
                'verbose_name': 'Магазины телеграмм бота',
                'verbose_name_plural': 'Магазины телеграмм бота',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('feedback', models.TextField(verbose_name='Сам отзыв')),
                ('answer', models.TextField(verbose_name='Ответ на отзыв')),
                ('feedback_id', models.CharField(max_length=100, verbose_name='Id отзыва')),
                ('day_answer', models.DateTimeField(verbose_name='Дата ответа на отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_answer', to='telebot.client', verbose_name='Пользователь, которому принадлежит ответ')),
            ],
        ),
    ]
