# Generated by Django 4.2 on 2023-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_client_time_notification_client_time_user_wbtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='feedbacks_send',
            field=models.BooleanField(default=True, verbose_name='Вкл/выкл уведомления для автоматических ответов'),
        ),
    ]
