# Generated by Django 4.2 on 2023-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_client_feedbacks_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackanswer',
            name='link_photos',
            field=models.TextField(null=True, verbose_name='Ссылки на фото отзывов'),
        ),
    ]
