# Generated by Django 4.2 on 2023-09-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_incorrectwbtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbtoken',
            name='use_sheet',
            field=models.BooleanField(default=False, verbose_name='Если True, используется Google Sheet'),
        ),
        migrations.CreateModel(
            name='GmailMarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, null=True, verbose_name='Ссылка на таблицу магазина')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_markets', to='telebot.wbtoken', verbose_name='Магазин, которому url')),
            ],
        ),
    ]
