# Generated by Django 4.2 on 2023-09-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0004_wbtoken_use_sheet_gmailmarkets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTriggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=100, verbose_name='Id отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('answer', models.TextField(verbose_name='Ответы')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('name_item', models.CharField(max_length=100, null=True, verbose_name='Название товара')),
                ('link_item', models.CharField(max_length=150, null=True, verbose_name='Ссылка на товар')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='telebot.wbtoken', verbose_name='Триггеры магазина')),
            ],
        ),
    ]
