# Generated by Django 4.2 on 2023-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0005_answertriggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertriggers',
            name='answered_feed',
            field=models.BooleanField(default=False, verbose_name='Состояние ответа на триггер'),
        ),
    ]
