# Generated by Django 4.2 on 2023-09-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0006_answertriggers_answered_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertriggers',
            name='trigger',
            field=models.CharField(max_length=20, null=True, verbose_name='Триггер'),
        ),
    ]
