# Generated by Django 4.2 on 2023-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0007_answertriggers_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackanswer',
            name='generated_mode',
            field=models.BooleanField(default=True, verbose_name='Режим генерации ответов GPT(T), Sheet(F)'),
        ),
    ]
