# Generated by Django 4.2 on 2023-09-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0008_feedbackanswer_generated_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertriggers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
