# Generated by Django 4.2 on 2023-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0009_answertriggers_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertriggers',
            name='link_feed',
            field=models.CharField(max_length=150, null=True, verbose_name='Ссылка на отзыв'),
        ),
    ]
